//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ApprovedPayroll
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApprovedPayroll()
        {
            this.ApprovedPayrollEmps = new HashSet<ApprovedPayrollEmp>();
        }
    
        public short Year { get; set; }
        public byte Month { get; set; }
        public int Serial { get; set; }
        public string MachineName { get; set; }
        public string UserId { get; set; }
        public bool CanEdit { get; set; }
        public Nullable<DateTime> Time { get; set; }
        public byte PaySlipId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public bool IsEmpsOpenedToEdit { get; set; }
    
        public virtual PaySlip PaySlip { get; set; }
        public virtual PaySlip PaySlip1 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedPayrollEmp> ApprovedPayrollEmps { get; set; }
    }
}
