//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class AttendanceGroupsView
    {
        public int AttendanceGroupId { get; set; }
        public string AttendanceGroupName { get; set; }
        public Nullable<byte> FromHourId { get; set; }
        public Nullable<byte> ToHourId { get; set; }
        public Nullable<DateTime> FromHour { get; set; }
        public Nullable<DateTime> ToHour { get; set; }
        public string AttendPermissionFrom { get; set; }
        public string AttendPermissionTo { get; set; }
        public Nullable<decimal> AttendPermission { get; set; }
        public string LeavePermissionFrom { get; set; }
        public string LeavePermissionTo { get; set; }
        public Nullable<decimal> LeavePermission { get; set; }
        public int DayId { get; set; }
        public byte AttendKind { get; set; }
    }
}
