//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class AttendanceGroups_9
    {
        public int AttendanceGroupId { get; set; }
        public string AttendanceGroupName { get; set; }
        public Nullable<byte> FromHourId { get; set; }
        public Nullable<byte> ToHourId { get; set; }
        public Nullable<DateTime> FromHour { get; set; }
        public Nullable<DateTime> ToHour { get; set; }
        public string AttendPermissionFrom { get; set; }
        public string AttendPermissionTo { get; set; }
        public Nullable<decimal> AttendPermission { get; set; }
        public string LeavePermissionFrom { get; set; }
        public string LeavePermissionTo { get; set; }
        public Nullable<decimal> LeavePermission { get; set; }
        public byte Saturday { get; set; }
        public byte Sunday { get; set; }
        public byte Monday { get; set; }
        public byte Tuesday { get; set; }
        public byte Wednesday { get; set; }
        public byte Thursday { get; set; }
        public byte Friday { get; set; }
        public string sFromHour { get; set; }
        public string sToHour { get; set; }
        public bool NextDay { get; set; }
        public Nullable<TimeSpan> StartSignIn { get; set; }
        public Nullable<TimeSpan> EndSignIn { get; set; }
        public Nullable<TimeSpan> StartSignOut { get; set; }
        public Nullable<TimeSpan> EndSignOut { get; set; }
        public bool SecurityGroup { get; set; }
    }
}
