//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class AttendanceGroup
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendanceGroup()
        {
            this.Attendances = new HashSet<Attendance>();
            this.AttendTrxes = new HashSet<AttendTrx>();
            this.AttendTrxEmployees = new HashSet<AttendTrxEmployee>();
            this.Employees = new HashSet<Employee>();
            this.SecurityAttSchds = new HashSet<SecurityAttSchd>();
            this.TmpAttendTrxes = new HashSet<TmpAttendTrx>();
            this.TmpAttendTrx2 = new HashSet<TmpAttendTrx2>();
        }
    
        public int AttendanceGroupId { get; set; }
        public string AttendanceGroupName { get; set; }
        public Nullable<byte> FromHourId { get; set; }
        public Nullable<byte> ToHourId { get; set; }
        public Nullable<DateTime> FromHour { get; set; }
        public Nullable<DateTime> ToHour { get; set; }
        public string AttendPermissionFrom { get; set; }
        public string AttendPermissionTo { get; set; }
        public Nullable<decimal> AttendPermission { get; set; }
        public string LeavePermissionFrom { get; set; }
        public string LeavePermissionTo { get; set; }
        public Nullable<decimal> LeavePermission { get; set; }
        public byte Saturday { get; set; }
        public byte Sunday { get; set; }
        public byte Monday { get; set; }
        public byte Tuesday { get; set; }
        public byte Wednesday { get; set; }
        public byte Thursday { get; set; }
        public byte Friday { get; set; }
        public string sFromHour { get; set; }
        public string sToHour { get; set; }
        public bool NextDay { get; set; }
        public Nullable<TimeSpan> StartSignIn { get; set; }
        public Nullable<TimeSpan> EndSignIn { get; set; }
        public Nullable<TimeSpan> StartSignOut { get; set; }
        public Nullable<TimeSpan> EndSignOut { get; set; }
        public bool SecurityGroup { get; set; }
        public bool HideAttGroup { get; set; }
        public bool Emergency { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendTrx> AttendTrxes { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendTrxEmployee> AttendTrxEmployees { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityAttSchd> SecurityAttSchds { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TmpAttendTrx> TmpAttendTrxes { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TmpAttendTrx2> TmpAttendTrx2 { get; set; }
    }
}
