//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class AttendTrxEmployee
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AttendTrxEmployee()
        {
            this.AttendTrxes = new HashSet<AttendTrx>();
            this.PermissionsTrxes = new HashSet<PermissionsTrx>();
            this.ShiftsTrxes = new HashSet<ShiftsTrx>();
            this.UpdateAttendTrxes = new HashSet<UpdateAttendTrx>();
            this.WorkDays = new HashSet<WorkDay>();
            this.WorkDaysTrxEmps = new HashSet<WorkDaysTrxEmp>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int DepartmentID { get; set; }
        public int AttendanceGroupId { get; set; }
        public bool NoAttendance { get; set; }
        public bool NotActive { get; set; }
        public string BioStarID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> JobTypeId { get; set; }
    
        public virtual AttendanceGroup AttendanceGroup { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendTrx> AttendTrxes { get; set; }
        public virtual Department Department { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual EmployeesTree EmployeesTree { get; set; }
        public virtual PermissionsSettingsD PermissionsSettingsD { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionsTrx> PermissionsTrxes { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftsTrx> ShiftsTrxes { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateAttendTrx> UpdateAttendTrxes { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDay> WorkDays { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDaysTrxEmp> WorkDaysTrxEmps { get; set; }
    }
}
