//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class BioStarTrx2
    {
        public int nDateTime { get; set; }
        public int nUserIdn { get; set; }
        public int nShiftIdn { get; set; }
        public int nDailyScheduleIdn { get; set; }
        public int nStartTime { get; set; }
        public int nEndTime { get; set; }
        public string sStartEvent { get; set; }
        public string sEndEvent { get; set; }
        public int nTAResult { get; set; }
        public int nWorkTime { get; set; }
        public int nIsModify { get; set; }
        public DateTime Date { get; set; }
    }
}
