//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class BonusEditEmp
    {
        public int Serial { get; set; }
        public short LineNo { get; set; }
        public int EmpId { get; set; }
        public string BonusId { get; set; }
        public decimal Amount { get; set; }
        public string Notes { get; set; }
        public byte Ratio { get; set; }
        public Nullable<byte> SalaryType { get; set; }
        public Nullable<byte> DaysCount { get; set; }
        public byte VacDays { get; set; }
        public Nullable<decimal> DeductAmount { get; set; }
    
        public virtual BonusEdit BonusEdit { get; set; }
        public virtual BonusList BonusList { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
