//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class BonusPayslip
    {
        public short Year { get; set; }
        public short Serial { get; set; }
        public byte LineNo { get; set; }
        public byte PaySlipID { get; set; }
        public bool Checked { get; set; }
    
        public virtual Bonu Bonu { get; set; }
    }
}
