//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class BonusCalculation
    {
        public short Year { get; set; }
        public short Serial { get; set; }
        public int EmpID { get; set; }
        public byte PaySlipID { get; set; }
        public byte PaySlipTypeID { get; set; }
        public short WorkDays { get; set; }
        public string Notes { get; set; }
        public decimal StartSalary { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal NatureAllow { get; set; }
        public decimal DamageAllow { get; set; }
        public decimal HighCostAllow { get; set; }
        public decimal OtherAllow { get; set; }
        public decimal Retirement { get; set; }
        public decimal Insurance { get; set; }
        public decimal BankLoan { get; set; }
        public decimal DaysDeduct { get; set; }
        public decimal DaysDeductValue { get; set; }
        public decimal HoursDeduct { get; set; }
        public decimal HoursDeductValue { get; set; }
        public decimal PenaltyDeduct { get; set; }
        public decimal OtherDeduct { get; set; }
        public decimal SumAllow { get; set; }
        public decimal SumDeduct { get; set; }
        public decimal Net { get; set; }
        public bool StopSalary { get; set; }
        public Nullable<decimal> Loan1 { get; set; }
        public Nullable<decimal> Loan2 { get; set; }
        public Nullable<decimal> Loan3 { get; set; }
        public decimal PenaltyDeductValue { get; set; }
        public decimal RetrievedRetirement { get; set; }
        public decimal AbsenceDays { get; set; }
        public decimal AbsenceDaysValue { get; set; }
        public decimal DaysSubtract { get; set; }
        public decimal DaysSubtractValue { get; set; }
        public Nullable<byte> Month { get; set; }
        public decimal CountDays { get; set; }
        public decimal CurSalary { get; set; }
        public Nullable<byte> BonusType { get; set; }
    
        public virtual Bonu Bonu { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
