//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Bonu
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonu()
        {
            this.BonusCalculations = new HashSet<BonusCalculation>();
            this.BonusPayslips = new HashSet<BonusPayslip>();
            this.Employees = new HashSet<Employee>();
        }
    
        public short Year { get; set; }
        public short Serial { get; set; }
        public decimal CountMonths { get; set; }
        public string Notes { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public string DateH { get; set; }
        public Nullable<DateTime> DueDate { get; set; }
        public string DueDateH { get; set; }
        public byte FilterType { get; set; }
        public Nullable<byte> Bank { get; set; }
        public Nullable<byte> TransType { get; set; }
        public Nullable<byte> Cal { get; set; }
        public byte SalaryType { get; set; }
        public decimal BonusRatio { get; set; }
        public Nullable<byte> Month { get; set; }
        public decimal CountDays { get; set; }
        public decimal BonusValue { get; set; }
        public string Statement { get; set; }
        public Nullable<byte> BonusType { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusCalculation> BonusCalculations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusPayslip> BonusPayslips { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
