//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CalculationsApproved
    {
        public short Year { get; set; }
        public byte Month { get; set; }
        public int EmpID { get; set; }
        public byte PaySlipID { get; set; }
        public byte PaySlipTypeID { get; set; }
        public short WorkDays { get; set; }
        public string Notes { get; set; }
        public decimal StartSalary { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal NatureAllow { get; set; }
        public decimal DamageAllow { get; set; }
        public decimal HighCostAllow { get; set; }
        public decimal OtherAllow { get; set; }
        public decimal Retirement { get; set; }
        public decimal Insurance { get; set; }
        public decimal BankLoan { get; set; }
        public decimal DaysDeduct { get; set; }
        public decimal DaysDeductValue { get; set; }
        public decimal HoursDeduct { get; set; }
        public decimal HoursDeductValue { get; set; }
        public decimal PenaltyDeduct { get; set; }
        public decimal OtherDeduct { get; set; }
        public decimal SumAllow { get; set; }
        public decimal SumDeduct { get; set; }
        public decimal Net { get; set; }
        public bool StopSalary { get; set; }
        public Nullable<decimal> Loan1 { get; set; }
        public Nullable<decimal> Loan2 { get; set; }
        public Nullable<decimal> Loan3 { get; set; }
        public decimal PenaltyDeductValue { get; set; }
        public decimal RetrievedRetirement { get; set; }
        public decimal AbsenceDays { get; set; }
        public decimal AbsenceDaysValue { get; set; }
        public decimal DaysSubtract { get; set; }
        public decimal DaysSubtractValue { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public decimal MilitaryServiceAllow { get; set; }
        public bool Delegated { get; set; }
        public decimal EmpSalary { get; set; }
        public decimal AbsenceHours { get; set; }
        public decimal AbsenceHoursValue { get; set; }
        public decimal OrgStartSalary { get; set; }
        public decimal OrgTransportAllow { get; set; }
        public decimal OrgHighCostAllow { get; set; }
        public decimal OrgNatureAllow { get; set; }
        public decimal AbsenceStartSalary { get; set; }
        public decimal AbsenceTransportAllow { get; set; }
        public decimal AbsenceHighCostAllow { get; set; }
        public decimal AbsenceNatureAllow { get; set; }
        public decimal OrgRetirement { get; set; }
        public decimal AbsenceRetirement { get; set; }
        public decimal EmpTransportAllow { get; set; }
        public decimal VacationAllow { get; set; }
        public decimal VacationAllowValue { get; set; }
        public decimal SupportDeduct { get; set; }
        public string BankShortName { get; set; }
        public byte AbsenceMins { get; set; }
        public byte MinsDeduct { get; set; }
        public decimal Bonus { get; set; }
        public decimal HealthInsurance { get; set; }
        public byte VacationDays { get; set; }
        public decimal TransVacDeduct { get; set; }
        public decimal PenaltyDays { get; set; }
        public decimal PenaltyDaysValue { get; set; }
        public byte PenaltyMin { get; set; }
        public byte PenaltyHours { get; set; }
        public decimal PenaltyHoursValue { get; set; }
        public int Serial { get; set; }
    }
}
