//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CalcAttendanceH
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalcAttendanceH()
        {
            this.CalcAttendanceFs = new HashSet<CalcAttendanceF>();
        }
    
        public short Year { get; set; }
        public byte Month { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalcAttendanceF> CalcAttendanceFs { get; set; }
    }
}
