//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CalculationsDetail
    {
        public short Year { get; set; }
        public byte Month { get; set; }
        public int EmpID { get; set; }
        public byte Serial { get; set; }
        public Nullable<byte> PaySlipID { get; set; }
        public Nullable<byte> PaySlipTypeID { get; set; }
        public short WorkDays { get; set; }
        public string Notes { get; set; }
        public decimal StartSalary { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal NatureAllow { get; set; }
        public decimal DamageAllow { get; set; }
        public decimal HighCostAllow { get; set; }
        public decimal OtherAllow { get; set; }
        public decimal Retirement { get; set; }
        public decimal Insurance { get; set; }
        public decimal BankLoan { get; set; }
        public decimal DaysDeduct { get; set; }
        public decimal DaysDeductValue { get; set; }
        public decimal HoursDeduct { get; set; }
        public decimal HoursDeductValue { get; set; }
        public decimal PenaltyDeduct { get; set; }
        public decimal OtherDeduct { get; set; }
        public decimal SumAllow { get; set; }
        public decimal SumDeduct { get; set; }
        public decimal Net { get; set; }
        public bool StopSalary { get; set; }
        public decimal Loan1 { get; set; }
        public decimal Loan2 { get; set; }
        public decimal Loan3 { get; set; }
        public Nullable<decimal> PenaltyDeductValue { get; set; }
        public Nullable<decimal> RetrievedRetirement { get; set; }
        public Nullable<decimal> AbsenceDays { get; set; }
        public Nullable<decimal> AbsenceDaysValue { get; set; }
        public Nullable<decimal> DaysSubtract { get; set; }
        public Nullable<decimal> DaysSubtractValue { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public Nullable<decimal> MilitaryServiceAllow { get; set; }
        public Nullable<bool> Delegated { get; set; }
        public Nullable<decimal> EmpSalary { get; set; }
        public Nullable<decimal> AbsenceHours { get; set; }
        public Nullable<decimal> AbsenceHoursValue { get; set; }
        public Nullable<decimal> OrgStartSalary { get; set; }
        public Nullable<decimal> OrgTransportAllow { get; set; }
        public Nullable<decimal> OrgHighCostAllow { get; set; }
        public Nullable<decimal> OrgNatureAllow { get; set; }
        public Nullable<decimal> AbsenceStartSalary { get; set; }
        public Nullable<decimal> AbsenceTransportAllow { get; set; }
        public Nullable<decimal> AbsenceHighCostAllow { get; set; }
        public Nullable<decimal> AbsenceNatureAllow { get; set; }
        public Nullable<decimal> OrgRetirement { get; set; }
        public Nullable<decimal> AbsenceRetirement { get; set; }
        public Nullable<decimal> EmpTransportAllow { get; set; }
        public Nullable<decimal> VacationAllow { get; set; }
        public Nullable<decimal> VacationAllowValue { get; set; }
        public Nullable<decimal> SupportDeduct { get; set; }
        public string BankShortName { get; set; }
        public Nullable<byte> AbsenceMins { get; set; }
        public Nullable<byte> MinsDeduct { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> HealthInsurance { get; set; }
        public Nullable<byte> VacationDays { get; set; }
        public Nullable<decimal> TransVacDeduct { get; set; }
    
        public virtual Calculation Calculation { get; set; }
    }
}
