//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CheckInOutDetail
    {
        public Nullable<int> EmpID { get; set; }
        public int USERID { get; set; }
        public Nullable<int> AttendanceGroupId { get; set; }
        public string AttendanceGroupName { get; set; }
        public Nullable<TimeSpan> StartSignIn { get; set; }
        public Nullable<TimeSpan> EndSignIn { get; set; }
        public Nullable<TimeSpan> StartSignOut { get; set; }
        public Nullable<TimeSpan> EndSignOut { get; set; }
        public Nullable<bool> NextDay { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public Nullable<TimeSpan> InTime { get; set; }
        public Nullable<TimeSpan> OutTime { get; set; }
        public Nullable<int> InSensorId { get; set; }
        public Nullable<int> OutSensorId { get; set; }
    }
}
