//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CHECKINOUTSQL
    {
        public int USERID { get; set; }
        public DateTime CHECKTIME { get; set; }
        public DateTime CHECKTIME2 { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public string DateH { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> AttendanceGroupId { get; set; }
        public Nullable<TimeSpan> StartSignIn { get; set; }
        public Nullable<TimeSpan> EndSignIn { get; set; }
        public Nullable<TimeSpan> StartSignOut { get; set; }
        public Nullable<TimeSpan> EndSignOut { get; set; }
        public Nullable<DateTime> InTimeDate { get; set; }
        public string InTime { get; set; }
        public Nullable<DateTime> OutTimeDate { get; set; }
        public string OutTime { get; set; }
    }
}
