//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CHECKINOUT
    {
        public int USERID { get; set; }
        public DateTime CHECKTIME { get; set; }
        public string CHECKTYPE { get; set; }
        public Nullable<int> VERIFYCODE { get; set; }
        public string SENSORID { get; set; }
        public Nullable<int> WorkCode { get; set; }
        public bool Uploaded { get; set; }
        public bool IsManual { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string MobileID { get; set; }
        public string ManualUserId { get; set; }
        public string ManualMachineName { get; set; }
        public Nullable<DateTime> ManualTime { get; set; }
    }
}
