//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CHECKINOUTVIEW
    {
        public DateTime CHECKTIME { get; set; }
        public int USERID { get; set; }
        public Nullable<DateTime> myDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<TimeSpan> myTime { get; set; }
        public bool Uploaded { get; set; }
    }
}
