//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CHECKINOUTSQLDate
    {
        public int USERID { get; set; }
        public DateTime CHECKTIME { get; set; }
        public Nullable<DateTime> InTimeD { get; set; }
        public Nullable<DateTime> OutTimeD { get; set; }
        public Nullable<DateTime> StartSignInD { get; set; }
        public Nullable<DateTime> EndSignInD { get; set; }
        public Nullable<DateTime> StartSignOutD { get; set; }
        public Nullable<DateTime> EndSignOutD { get; set; }
    }
}
