//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Class
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Degrees = new HashSet<Degree>();
        }
    
        public byte ClassID { get; set; }
        public byte DegreesCount { get; set; }
        public decimal YearlyIncrease { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal InsideLegationAllow { get; set; }
        public decimal OutsideLegationAllow { get; set; }
        public decimal StartSalary { get; set; }
        public string ClassName { get; set; }
        public byte InsuranceAndRetirement { get; set; }
        public bool HasNatureAllow { get; set; }
        public bool HasDamageAllow { get; set; }
        public bool HasHighCostAllow { get; set; }
        public decimal OutsideLegationAllow1 { get; set; }
        public decimal OutsideLegationAllow2 { get; set; }
        public decimal OutsideLegationAllow3 { get; set; }
        public string RankCode { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Degree> Degrees { get; set; }
    }
}
