//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Customer
    {
        public byte TypeId { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string IdNo { get; set; }
        public Nullable<DateTime> IdEndDate { get; set; }
        public string IdEndDateH { get; set; }
        public Nullable<byte> IdTypeId { get; set; }
        public string IdCity { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string WorkPhone { get; set; }
        public string Fax { get; set; }
        public string Job { get; set; }
        public Nullable<short> NatId { get; set; }
        public Nullable<short> ReligionId { get; set; }
        public Nullable<DateTime> BirthDate { get; set; }
        public string BirthDateH { get; set; }
        public Nullable<DateTime> BirthDateG { get; set; }
        public string BirthDateGH { get; set; }
        public string EMail { get; set; }
        public string CommercialRegister { get; set; }
        public string CommRegCity { get; set; }
        public Nullable<DateTime> CommRegDate { get; set; }
        public string CommRegDateH { get; set; }
        public string PostalCode { get; set; }
        public string PostBox { get; set; }
        public string PBoxCity { get; set; }
        public bool BlackList { get; set; }
        public byte[] WorkerPicture { get; set; }
        public string Description { get; set; }
        public string Representative { get; set; }
        public string ReprsnPosition { get; set; }
        public string OldIdNo { get; set; }
        public bool Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string FamilyMemCount { get; set; }
        public Nullable<DateTime> IdIssueDate { get; set; }
        public string IdIssueDateH { get; set; }
        public Nullable<DateTime> OldIdNoEndDate { get; set; }
        public string OldIdNoEndDateH { get; set; }
        public string MobileCCode { get; set; }
        public string District { get; set; }
        public string Street { get; set; }
    }
}
