//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class CustomPayroll
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomPayroll()
        {
            this.CustomPayrollEmps = new HashSet<CustomPayrollEmp>();
        }
    
        public short Year { get; set; }
        public byte Month { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte PaySlipId { get; set; }
        public string Notes { get; set; }
    
        public virtual PaySlip PaySlip { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomPayrollEmp> CustomPayrollEmps { get; set; }
    }
}
