//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecesionAbsenceNormalDeduction
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DecesionAbsenceNormalDeduction()
        {
            this.DecesionAbsenceNormalDeductionDays = new HashSet<DecesionAbsenceNormalDeductionDay>();
        }
    
        public int AbsenceNormalDeductionSerial { get; set; }
        public string AbsenceNormalDeductionID { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public int EmpId { get; set; }
        public short VacationPeriod { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public Nullable<DateTime> StartService { get; set; }
        public string StartServiceH { get; set; }
        public Nullable<DateTime> EndService { get; set; }
        public string EndServiceH { get; set; }
        public Nullable<bool> PayVacationSalary { get; set; }
        public Nullable<int> SubstituteEmpId { get; set; }
        public Nullable<short> VacationApplicationYear { get; set; }
        public Nullable<int> VacationApplicationSerial { get; set; }
        public Nullable<short> VacationYear { get; set; }
        public Nullable<int> VacationSerial { get; set; }
        public bool Deleted { get; set; }
        public string Notes { get; set; }
        public bool ExpandNormalVacation { get; set; }
        public string Description { get; set; }
        public bool ContinuousDays { get; set; }
        public Nullable<byte> ReplacementType { get; set; }
        public Nullable<byte> Hours { get; set; }
        public string EltezamResponse { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Owner Owner { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecesionAbsenceNormalDeductionDay> DecesionAbsenceNormalDeductionDays { get; set; }
    }
}
