//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionWorkerVacation
    {
        public int DecisionWorkerVacationSerial { get; set; }
        public string DecisionWorkerVacationNo { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public int EmpId { get; set; }
        public short VacationPeriod { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public DateTime StartService { get; set; }
        public string StartServiceH { get; set; }
        public DateTime EndService { get; set; }
        public string EndServiceH { get; set; }
        public decimal VacationSalary { get; set; }
        public string Notes { get; set; }
        public short WorkDays { get; set; }
        public decimal DeservedSalary { get; set; }
        public short ExceptionVacPeriod { get; set; }
        public Nullable<short> VacationApplicationYear { get; set; }
        public Nullable<int> VacationApplicationSerial { get; set; }
        public bool GeneralBalance { get; set; }
        public bool AddVacDays { get; set; }
        public Nullable<decimal> Ticket { get; set; }
        public bool Deleted { get; set; }
        public string DeleteReason { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
