//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionResumeWork
    {
        public int DecisionResumeWorkID { get; set; }
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public string Manager { get; set; }
        public string ManagementDecisionNo { get; set; }
        public Nullable<DateTime> ManagementDecisionDate { get; set; }
        public string ManagementDecisionDateH { get; set; }
        public string System { get; set; }
        public string BackFrom { get; set; }
        public Nullable<DateTime> LastServiceDate { get; set; }
        public string LastServiceDateH { get; set; }
        public Nullable<short> VacationPeriod { get; set; }
        public string Notes { get; set; }
        public byte VacType { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        public virtual Vacation Vacation { get; set; }
    }
}
