//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionEndStopHand
    {
        public int DecisionEndStopHandID { get; set; }
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public string PublishedFrom { get; set; }
        public int PublishNumber { get; set; }
        public DateTime PublishDate { get; set; }
        public string PublishDateH { get; set; }
        public string Subject { get; set; }
        public string Approval { get; set; }
        public string Reason { get; set; }
        public DateTime StartDate { get; set; }
        public string StartDateH { get; set; }
        public DateTime SalaryStartDate { get; set; }
        public string SalaryStartDateH { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
