//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionEndService
    {
        public short EndServiceYear { get; set; }
        public int EndServiceSerial { get; set; }
        public int DecisionEndServiceID { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public string DependOn { get; set; }
        public string Reason { get; set; }
        public string SystemDeserved { get; set; }
        public DateTime EndWorkDate { get; set; }
        public string EndWorkDateH { get; set; }
        public decimal VacationBalance { get; set; }
        public decimal EndServiceBonus { get; set; }
        public decimal VacationBonus { get; set; }
        public byte EndServiceTypeId { get; set; }
        public byte ServiceDays { get; set; }
        public byte ServiceMonths { get; set; }
        public byte ServiceYears { get; set; }
        public decimal FiveYearsValue { get; set; }
        public decimal RestYearsValue { get; set; }
        public decimal FractionYears { get; set; }
        public decimal DeservedVacations { get; set; }
        public short TakenVacations { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Ticket { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Owner Owner1 { get; set; }
    }
}
