//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionAbsenceDeduction
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DecisionAbsenceDeduction()
        {
            this.DecisionAbsenceDeductionFooters = new HashSet<DecisionAbsenceDeductionFooter>();
        }
    
        public int DecisionAbsenceDeductionID { get; set; }
        public string Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int DepartmentId { get; set; }
        public string LetterId { get; set; }
        public DateTime LetterDate { get; set; }
        public string LetterDateH { get; set; }
        public short EmpCount { get; set; }
        public string Notes { get; set; }
        public string AbsenceMonth { get; set; }
        public string DeductMonth { get; set; }
        public string Reason { get; set; }
        public Nullable<byte> AbsenceMonthNo { get; set; }
        public Nullable<byte> DeductMonthNo { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> ReplacementType { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        public virtual Department Department { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionAbsenceDeductionFooter> DecisionAbsenceDeductionFooters { get; set; }
    }
}
