//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionExceptionVacation
    {
        public int DecisionExceptionVacationID { get; set; }
        public string Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public short VacationPeriod { get; set; }
        public string Subject { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public string Notes { get; set; }
        public string BasedOn { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public byte ReplacementType { get; set; }
        public string EltezamResponse { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
