//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionOutOfDutySpendF
    {
        public int OutOfDutySpendSerial { get; set; }
        public int EmpId { get; set; }
        public decimal Salary { get; set; }
        public decimal TransAllow { get; set; }
        public decimal SumNormal { get; set; }
        public decimal SumVac { get; set; }
        public decimal Total { get; set; }
        public int Serial { get; set; }
        public byte VacDays { get; set; }
        public byte LegationDays { get; set; }
        public string Notes { get; set; }
    
        public virtual DecisionOutOfDutySpend DecisionOutOfDutySpend { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
