//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionNormalVacation_ROW_NUMBER
    {
        public Nullable<long> Serial { get; set; }
        public Nullable<int> DecisionNormalVacationSerial { get; set; }
        public string DecisionNormalVacationID { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public Nullable<int> Owner { get; set; }
        public int EmpId { get; set; }
        public short VacationPeriod { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public Nullable<DateTime> StartService { get; set; }
        public string StartServiceH { get; set; }
        public Nullable<DateTime> EndService { get; set; }
        public string EndServiceH { get; set; }
        public Nullable<bool> PayVacationSalary { get; set; }
        public Nullable<int> SubstituteEmpId { get; set; }
        public Nullable<short> VacationApplicationYear { get; set; }
        public Nullable<int> VacationApplicationSerial { get; set; }
        public Nullable<short> VacationYear { get; set; }
        public Nullable<int> VacationSerial { get; set; }
        public bool Deleted { get; set; }
        public string Notes { get; set; }
    }
}
