//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionLongLegation
    {
        public int DecisionLongLegationId { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public int EmpId { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public string Notes { get; set; }
        public Nullable<short> Period { get; set; }
        public string DecisionNo { get; set; }
        public string Location { get; set; }
        public bool ExpandDecisionLegation { get; set; }
        public Nullable<int> OldDecisionLongLegationId { get; set; }
        public string OldDecisionNo { get; set; }
        public Nullable<DateTime> OldDecisionDate { get; set; }
        public string OldDecisionDateH { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    }
}
