//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionChangeJob
    {
        public int DecisionChangeJobID { get; set; }
        public Nullable<int> Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public string LetterId { get; set; }
        public DateTime LetterDate { get; set; }
        public string LetterDateH { get; set; }
        public short JobId { get; set; }
        public byte ClassId { get; set; }
        public byte DegreeId { get; set; }
        public int DepartmentID { get; set; }
        public DateTime StartDate { get; set; }
        public string StartDateH { get; set; }
        public Nullable<int> OldFormingNumer { get; set; }
        public Nullable<int> NewFormingNumer { get; set; }
        public string ApprovalDepartment { get; set; }
        public string Notes { get; set; }
        public string AccordingTo { get; set; }
        public string ApprovalDepartmentPlace { get; set; }
        public string OldClassificationNo { get; set; }
        public string NewClassificationNo { get; set; }
        public Nullable<int> OldJobSerial { get; set; }
        public Nullable<int> NewJobSerial { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FixedJob FixedJob { get; set; }
        public virtual FixedJob FixedJob1 { get; set; }
    }
}
