//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionCompanionVac
    {
        public int CompanionVacationSerial { get; set; }
        public string CompanionVacationID { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public int EmpId { get; set; }
        public short VacationPeriod { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public Nullable<DateTime> StartService { get; set; }
        public string StartServiceH { get; set; }
        public Nullable<DateTime> EndService { get; set; }
        public string EndServiceH { get; set; }
        public string CompanionName { get; set; }
        public string CompanionDescription { get; set; }
        public string Reason { get; set; }
        public string Place { get; set; }
        public string MedicalLetterNo { get; set; }
        public Nullable<DateTime> MedicalLetterDate { get; set; }
        public string MedicalLetterDateH { get; set; }
        public Nullable<short> VacationApplicationYear { get; set; }
        public Nullable<int> VacationApplicationSerial { get; set; }
        public string Notes { get; set; }
        public Nullable<byte> ReplacementType { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual VacationApplication VacationApplication { get; set; }
    }
}
