//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionWorkerVacationView
    {
        public int DecisionWorkerVacationSerial { get; set; }
        public string DecisionWorkerVacationNo { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string JobName { get; set; }
        public string ClassName { get; set; }
        public Nullable<decimal> StartSalary { get; set; }
        public short VacationPeriod { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public DateTime StartService { get; set; }
        public string StartServiceH { get; set; }
        public DateTime EndService { get; set; }
        public string EndServiceH { get; set; }
        public decimal VacationSalary { get; set; }
        public string Notes { get; set; }
        public short WorkDays { get; set; }
        public decimal DeservedSalary { get; set; }
    }
}
