//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionMoveEmp
    {
        public int DecisionMoveEmpID { get; set; }
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public DateTime StartDate { get; set; }
        public string StartDateH { get; set; }
        public int LetterId { get; set; }
        public DateTime LetterDate { get; set; }
        public string LetterDateH { get; set; }
        public DateTime StartWorkDate { get; set; }
        public string StartWorkDateH { get; set; }
        public string Place { get; set; }
        public string BasedOn { get; set; }
        public string Notes { get; set; }
        public bool PayReward { get; set; }
        public string PayRewardDesc { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
