//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecisionEmployment
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DecisionEmployment()
        {
            this.DecisionEmploymentFooters = new HashSet<DecisionEmploymentFooter>();
        }
    
        public int DecisionEmploymentID { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public string DependOn { get; set; }
        public int EmpId { get; set; }
        public bool MonthSalary { get; set; }
        public bool OnTrial { get; set; }
        public Nullable<int> Owner2 { get; set; }
        public string Notes { get; set; }
        public string DecisionNo { get; set; }
        public string ClassificationNo { get; set; }
        public Nullable<int> JobSerial { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FixedJob FixedJob { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionEmploymentFooter> DecisionEmploymentFooters { get; set; }
    }
}
