//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class DecResumeWorkVacsSearch
    {
        public int VacType { get; set; }
        public int ManagementDecisionNo { get; set; }
        public string EmpName { get; set; }
        public short VacationPeriod { get; set; }
        public string FromDateH { get; set; }
        public string ToDateH { get; set; }
    }
}
