//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Department
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.AttendTrxEmployees = new HashSet<AttendTrxEmployee>();
            this.DecisionAbsenceDeductions = new HashSet<DecisionAbsenceDeduction>();
            this.Employees = new HashSet<Employee>();
            this.FixedJobs = new HashSet<FixedJob>();
            this.PermissionsSettingsDs = new HashSet<PermissionsSettingsD>();
            this.SuddenFPs = new HashSet<SuddenFP>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendTrxEmployee> AttendTrxEmployees { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionAbsenceDeduction> DecisionAbsenceDeductions { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedJob> FixedJobs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionsSettingsD> PermissionsSettingsDs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuddenFP> SuddenFPs { get; set; }
    }
}
