//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class EmpCard
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpNameEn { get; set; }
        public string IDNumber { get; set; }
        public string IDPlace { get; set; }
        public Nullable<DateTime> CardEndDate { get; set; }
        public string CardEndDateH { get; set; }
        public byte[] EmployeeImage { get; set; }
        public string JobName { get; set; }
        public Nullable<DateTime> CardIssueDate { get; set; }
        public string CardIssueDateH { get; set; }
        public string Mobile1 { get; set; }
    }
}
