//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class EmpDisclaimer
    {
        public int EmpDisclaimerSerial { get; set; }
        public string EmpDisclaimerNo { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public int EmpId { get; set; }
        public string Notes { get; set; }
        public bool AnyCustodyExist { get; set; }
        public string CustodyDescription { get; set; }
        public byte WorkCardExist { get; set; }
        public byte EmpCustodyExist { get; set; }
        public byte FinanceCustodyExist { get; set; }
        public byte StoresCustodyExist { get; set; }
        public byte ServicesCustodyExist { get; set; }
        public Nullable<int> EmpManagerId { get; set; }
        public Nullable<int> FinanceManagerId { get; set; }
        public Nullable<int> StoreEmpId1 { get; set; }
        public Nullable<int> StoreEmpId2 { get; set; }
        public Nullable<int> ServicesEmpId { get; set; }
        public Nullable<int> SpecialistEmpId { get; set; }
        public string NotesFinance { get; set; }
        public string Reasons { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
