//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class EmployeeService
    {
        public int EmpID { get; set; }
        public int LineNo { get; set; }
        public Nullable<int> JobID { get; set; }
        public string ClassName { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public Nullable<decimal> StartSalary { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<DateTime> StartService { get; set; }
        public string StartServiceH { get; set; }
        public Nullable<DateTime> EndService { get; set; }
        public string EndServiceH { get; set; }
        public string Reasons { get; set; }
        public string OrderNo { get; set; }
        public Nullable<DateTime> OrderDate { get; set; }
        public string OrderDateH { get; set; }
        public string Notes { get; set; }
        public string JobNo { get; set; }
        public Nullable<int> PromotionID { get; set; }
        public string ClassificationNo { get; set; }
        public Nullable<DateTime> SeparateDate { get; set; }
        public string SeparateDateH { get; set; }
        public Nullable<int> DecisionEmploymentId { get; set; }
        public Nullable<int> DecisionChangeJobID { get; set; }
        public Nullable<int> YearlyIncreaseYear { get; set; }
        public Nullable<int> DecisionYearlyIncreaseID { get; set; }
        public Nullable<byte> LocationCode { get; set; }
        public string TransactionCode { get; set; }
        public string EltezamResponse { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmpPromotion EmpPromotion { get; set; }
        public virtual EmpTransaction EmpTransaction { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobLocation JobLocation { get; set; }
    }
}
