//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class EmpPermission
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpPermission()
        {
            this.EmpPermissionsDetails = new HashSet<EmpPermissionsDetail>();
        }
    
        public short Year { get; set; }
        public int Serial { get; set; }
        public DateTime PermissionDate { get; set; }
        public string PermissionDateH { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public string Notes { get; set; }
        public bool ChiefSignature { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPermissionsDetail> EmpPermissionsDetails { get; set; }
    }
}
