//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class FixedJobsView
    {
        public int JobSerial { get; set; }
        public string JobName { get; set; }
        public string JobNo { get; set; }
        public string ClassificationNo { get; set; }
        public byte ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public string JobLocation { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<DateTime> JobDate { get; set; }
        public string JobDateH { get; set; }
        public bool JobStatus { get; set; }
        public Nullable<DateTime> VacantDate { get; set; }
        public string VacantDateH { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<short> NatId { get; set; }
        public string NatName { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> JobID { get; set; }
        public string Jobs_JobName { get; set; }
        public Nullable<byte> JobLocationID { get; set; }
        public string JobLocationName { get; set; }
    }
}
