//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class FixedJob
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedJob()
        {
            this.DecisionChangeJobs = new HashSet<DecisionChangeJob>();
            this.DecisionChangeJobs1 = new HashSet<DecisionChangeJob>();
            this.DecisionEmployments = new HashSet<DecisionEmployment>();
            this.DecisionNewJobs = new HashSet<DecisionNewJob>();
            this.EmpPromotions = new HashSet<EmpPromotion>();
            this.EmpPromotions1 = new HashSet<EmpPromotion>();
        }
    
        public int JobSerial { get; set; }
        public string JobName { get; set; }
        public string JobNo { get; set; }
        public string ClassificationNo { get; set; }
        public byte ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public string JobLocation { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<DateTime> JobDate { get; set; }
        public string JobDateH { get; set; }
        public bool JobStatus { get; set; }
        public Nullable<DateTime> VacantDate { get; set; }
        public string VacantDateH { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<byte> JobLocationID { get; set; }
        public Nullable<byte> PaySlipID { get; set; }
        public string JobTrancsactionCode { get; set; }
        public string EltezamResponse { get; set; }
        public Nullable<DateTime> EndDate { get; set; }
        public string EndDateH { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionChangeJob> DecisionChangeJobs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionChangeJob> DecisionChangeJobs1 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionEmployment> DecisionEmployments { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionNewJob> DecisionNewJobs { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPromotion> EmpPromotions { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPromotion> EmpPromotions1 { get; set; }
        public virtual JobLocation JobLocation1 { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobTransaction JobTransaction { get; set; }
    }
}
