//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Holiday
    {
        public short Year { get; set; }
        public byte HolidayNo { get; set; }
        public string HolidayName { get; set; }
        public DateTime StartDate { get; set; }
        public string StartDateH { get; set; }
        public byte Days { get; set; }
        public DateTime EndDate { get; set; }
        public string EndDateH { get; set; }
        public string Notes { get; set; }
        public byte PaySlipId { get; set; }
    
        public virtual PaySlipGroup PaySlipGroup { get; set; }
    }
}
