//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationSpendView
    {
        public int LegationSpendSerial { get; set; }
        public string LegationSpendNo { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public string Notes { get; set; }
        public bool LegationType { get; set; }
        public string LegationTypeName { get; set; }
        public string OutlegationTypeName { get; set; }
        public Nullable<byte> OutlegationType { get; set; }
        public short NightsCount { get; set; }
        public string FromDateH { get; set; }
        public DateTime FromDate { get; set; }
        public string ToDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string LegationLocation { get; set; }
        public string Mission { get; set; }
        public Nullable<byte> TravelTypeId { get; set; }
        public string TravelTypeName { get; set; }
        public Nullable<int> LegationGroupSerial { get; set; }
        public string TravelDistance { get; set; }
        public bool Travel { get; set; }
        public bool Housing { get; set; }
        public bool Food { get; set; }
        public bool Transport { get; set; }
        public bool Taxi { get; set; }
        public bool TicketsValue { get; set; }
        public bool DailyTrans { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> NightsRatio { get; set; }
        public Nullable<decimal> TotalNights { get; set; }
        public Nullable<decimal> TransportAllow { get; set; }
        public Nullable<decimal> Tickets { get; set; }
        public Nullable<decimal> TotalLegation { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string IDNumber { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<byte> PaySlipID { get; set; }
        public string DepartmentName { get; set; }
    }
}
