//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationSpendF2
    {
        public int LegationSpendSerial { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> LegationGroupSerial { get; set; }
        public byte LegationType { get; set; }
        public Nullable<byte> OutlegationType { get; set; }
        public short NightsCount { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public string LegationLocation { get; set; }
        public string Mission { get; set; }
        public Nullable<byte> TravelTypeId { get; set; }
        public string TravelDistance { get; set; }
        public decimal NightsRatio { get; set; }
        public decimal TotalNights { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal Tickets { get; set; }
        public decimal TotalLegation { get; set; }
        public int SerialNo { get; set; }
        public string Notes { get; set; }
        public int LineNo { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LegationGroup LegationGroup { get; set; }
        public virtual LegationSpend2 LegationSpend2 { get; set; }
        public virtual TravelType TravelType { get; set; }
    }
}
