//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationApplication
    {
        public short Year { get; set; }
        public int LegationSerial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public int EmpId { get; set; }
        public short LegationPeriod { get; set; }
        public string LegationLocation { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public string Reason { get; set; }
        public Nullable<byte> TravelTypeId { get; set; }
        public string RequestingPlace { get; set; }
        public string Section { get; set; }
        public Nullable<byte> Approval { get; set; }
        public decimal Amount { get; set; }
        public bool Obligated { get; set; }
        public Nullable<DateTime> ObligationDate { get; set; }
        public string ObligationDateH { get; set; }
        public string RefuseReason { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Notes { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<bool> AssignedWorkAtWorkTime { get; set; }
        public Nullable<decimal> TravelCosts { get; set; }
        public Nullable<decimal> ErcapCosts { get; set; }
        public Nullable<decimal> TransportCosts { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TravelType TravelType { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
