//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationSpend
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegationSpend()
        {
            this.Legations = new HashSet<Legation>();
            this.LegationSpendFs = new HashSet<LegationSpendF>();
        }
    
        public int LegationSpendSerial { get; set; }
        public string LegationSpendNo { get; set; }
        public Nullable<int> LegationGroupSerial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public string Notes { get; set; }
        public bool LegationType { get; set; }
        public Nullable<byte> OutlegationType { get; set; }
        public short NightsCount { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public string LegationLocation { get; set; }
        public string Mission { get; set; }
        public Nullable<byte> TravelTypeId { get; set; }
        public string TravelDistance { get; set; }
        public bool Travel { get; set; }
        public bool Housing { get; set; }
        public bool Food { get; set; }
        public bool Transport { get; set; }
        public bool Taxi { get; set; }
        public bool TicketsValue { get; set; }
        public bool DailyTrans { get; set; }
        public bool SentFinance { get; set; }
    
        public virtual LegationGroup LegationGroup { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Legation> Legations { get; set; }
        public virtual TravelType TravelType { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegationSpendF> LegationSpendFs { get; set; }
    }
}
