//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationsView
    {
        public short Year { get; set; }
        public byte Month { get; set; }
        public int SerialNo { get; set; }
        public string LegationID { get; set; }
        public int EmpID { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public string DateH { get; set; }
        public bool LegationType { get; set; }
        public string LegationTypeName { get; set; }
        public Nullable<byte> OutlegationType { get; set; }
        public string OutlegationTypeName { get; set; }
        public short NightsCount { get; set; }
        public decimal NightsRatio { get; set; }
        public decimal TotalNights { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal Tickets { get; set; }
        public decimal TotalLegation { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public string LegationLocation { get; set; }
        public bool Travel { get; set; }
        public bool Housing { get; set; }
        public bool Food { get; set; }
        public bool Transport { get; set; }
        public string Notes { get; set; }
        public Nullable<short> LegationApplicationYear { get; set; }
        public Nullable<int> LegationApplicationSerial { get; set; }
        public string Mission { get; set; }
        public Nullable<byte> TravelTypeId { get; set; }
        public string TicketNo { get; set; }
        public string FlightNo { get; set; }
        public Nullable<DateTime> ReturnDate { get; set; }
        public string ReturnDateH { get; set; }
        public string ReturnFlightNo { get; set; }
        public bool TicketsValue { get; set; }
        public bool Taxi { get; set; }
        public bool DailyTrans { get; set; }
        public Nullable<int> LegationSpendSerial { get; set; }
        public decimal CarFare { get; set; }
        public Nullable<long> ApplicationNo { get; set; }
        public Nullable<DateTime> ApplicationDate { get; set; }
        public string ApplicationDateH { get; set; }
        public string EmpName { get; set; }
        public string JobName { get; set; }
        public Nullable<decimal> EmpTransportAllow { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public string ClassName { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPosition { get; set; }
        public string TravelTypeName { get; set; }
    }
}
