//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationApplicationView
    {
        public short Year { get; set; }
        public int LegationSerial { get; set; }
        public string DateH { get; set; }
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public short LegationPeriod { get; set; }
        public string LegationLocation { get; set; }
        public string FromDateH { get; set; }
        public string ToDateH { get; set; }
        public string Reason { get; set; }
        public Nullable<byte> TravelTypeId { get; set; }
        public string TravelTypeName { get; set; }
        public string RequestingPlace { get; set; }
        public string Section { get; set; }
        public string ApprovalText { get; set; }
        public Nullable<byte> Approval { get; set; }
        public decimal Amount { get; set; }
        public string ObligatedText { get; set; }
        public bool Obligated { get; set; }
        public string ObligationDateH { get; set; }
        public string RefuseReason { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public Nullable<decimal> StartSalary { get; set; }
        public string ClassName { get; set; }
        public string JobName { get; set; }
        public Nullable<decimal> TransportAllow { get; set; }
        public string NatName { get; set; }
        public string DepartmentName { get; set; }
        public string JobLocationName { get; set; }
        public string CurrentDepartmentName { get; set; }
        public string CurrentJobName { get; set; }
    }
}
