//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationSpend2
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegationSpend2()
        {
            this.Legations = new HashSet<Legation>();
            this.LegationSpendF2 = new HashSet<LegationSpendF2>();
        }
    
        public int LegationSpendSerial { get; set; }
        public string LegationSpendNo { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public string Notes { get; set; }
        public bool Travel { get; set; }
        public bool Housing { get; set; }
        public bool Food { get; set; }
        public bool Transport { get; set; }
        public bool Taxi { get; set; }
        public bool TicketsValue { get; set; }
        public bool DailyTrans { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Legation> Legations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegationSpendF2> LegationSpendF2 { get; set; }
    }
}
