//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationGroup
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegationGroup()
        {
            this.LegationSpends = new HashSet<LegationSpend>();
            this.LegationSpendF2 = new HashSet<LegationSpendF2>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int LegationGroupSerial { get; set; }
        public string LegationGroupNo { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public short LegationPeriod { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public string LegationLocation { get; set; }
        public string Mission { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> LegationType { get; set; }
        public Nullable<byte> OutlegationType { get; set; }
        public bool NoSpend { get; set; }
        public bool Taxi { get; set; }
        public bool TicketsValue { get; set; }
        public bool DailyTrans { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
        public Nullable<bool> ChiefSignature { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string OutDecisionsNo { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegationSpend> LegationSpends { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegationSpendF2> LegationSpendF2 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
