//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class LegationSpendView2
    {
        public int LegationSpendSerial { get; set; }
        public string LegationSpendNo { get; set; }
        public string DateH { get; set; }
        public string LegationTypeName { get; set; }
        public Nullable<short> NightsCount { get; set; }
        public string FromDateH { get; set; }
        public string ToDateH { get; set; }
        public string EmpName { get; set; }
    }
}
