//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class MarriageVac
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarriageVac()
        {
            this.VacationTrxes = new HashSet<VacationTrx>();
        }
    
        public short MrVacSerial { get; set; }
        public int DecisionNo { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public short VacationPeriod { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Owner Owner1 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationTrx> VacationTrxes { get; set; }
    }
}
