//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class MedicalExaminationView
    {
        public int MedicalSerial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EmpStatus { get; set; }
        public Nullable<DateTime> AbsenceDate { get; set; }
        public string AbsenceDateH { get; set; }
        public string MedicalUnitName { get; set; }
        public string Notes { get; set; }
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public byte PaySlipID { get; set; }
        public string PaySlipName { get; set; }
        public string DepartmentName { get; set; }
        public string ClassName { get; set; }
        public string JobName { get; set; }
        public string EmpStatusName { get; set; }
    }
}
