//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Menu
    {
        public byte SystemId { get; set; }
        public short MenuId { get; set; }
        public short ParentId { get; set; }
        public string Caption { get; set; }
        public string FormName { get; set; }
        public string ImageName { get; set; }
        public string ShortCutKeys { get; set; }
        public bool LastSub { get; set; }
        public string Parameter { get; set; }
        public string FormCaledarType { get; set; }
    }
}
