//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class OutOfDutyView
    {
        public short Year { get; set; }
        public byte Month { get; set; }
        public int Serial { get; set; }
        public int EmpID { get; set; }
        public byte NormalDays { get; set; }
        public byte Hours { get; set; }
        public byte Minutes { get; set; }
        public decimal SumNormal { get; set; }
        public byte VacDays { get; set; }
        public byte VacHours { get; set; }
        public byte VacMinutes { get; set; }
        public decimal SumVac { get; set; }
        public decimal TransAllow { get; set; }
        public decimal Total { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public string DateH { get; set; }
        public decimal NormalMonthes { get; set; }
        public decimal VacMonthes { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> OutOfDutySpendSerial { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public string EmpName { get; set; }
        public string JobName { get; set; }
        public string DepartmentName { get; set; }
        public string ClassName { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
    }
}
