//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class OutOfDutySpendView2
    {
        public int OutOfDutySpendSerial { get; set; }
        public string OutOfDutySpendNo { get; set; }
        public Nullable<int> OutOfDutyGroupSerial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public Nullable<byte> EnclosureCount { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<byte> NormalDays { get; set; }
        public Nullable<byte> Hours { get; set; }
        public Nullable<byte> Minutes { get; set; }
        public Nullable<byte> VacDaysF { get; set; }
        public Nullable<byte> VacHours { get; set; }
        public Nullable<byte> VacMinutes { get; set; }
        public string Notes { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public string Task { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPosition { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> TransAllow { get; set; }
        public Nullable<decimal> SumNormal { get; set; }
        public Nullable<decimal> SumVac { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Serial { get; set; }
        public string EmpName { get; set; }
        public Nullable<byte> ClassID { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public string JobName { get; set; }
        public string DepartmentName { get; set; }
        public string ClassName { get; set; }
    }
}
