//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class OutOfDuty
    {
        public short Year { get; set; }
        public byte Month { get; set; }
        public int Serial { get; set; }
        public int EmpID { get; set; }
        public byte NormalDays { get; set; }
        public byte Hours { get; set; }
        public byte Minutes { get; set; }
        public decimal SumNormal { get; set; }
        public byte VacDays { get; set; }
        public byte VacHours { get; set; }
        public byte VacMinutes { get; set; }
        public decimal SumVac { get; set; }
        public decimal TransAllow { get; set; }
        public decimal Total { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public string DateH { get; set; }
        public decimal NormalMonthes { get; set; }
        public decimal VacMonthes { get; set; }
        public decimal Salary { get; set; }
        public Nullable<int> OutOfDutySpendSerial { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public byte NormalDeduct { get; set; }
        public decimal NormalDeductValue { get; set; }
        public byte VacDeduct { get; set; }
        public decimal VacDeductValue { get; set; }
        public Nullable<int> SingleOutOfDutySerial { get; set; }
        public string Mission { get; set; }
        public string Notes { get; set; }
        public Nullable<int> OutOfDutySpendSerial2 { get; set; }
    
        public virtual DecisionOutOfDutySpend DecisionOutOfDutySpend { get; set; }
        public virtual DecisionOutOfDutySpend2 DecisionOutOfDutySpend2 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
