//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Outsider
    {
        public int OutsiderId { get; set; }
        public string EmpName { get; set; }
        public short NatId { get; set; }
        public string NatName { get; set; }
        public int JobID { get; set; }
        public string JobName { get; set; }
        public string IDNumber { get; set; }
        public int AttendanceGroupId { get; set; }
        public string AttendanceGroupName { get; set; }
        public string OutsiderLegationLocation { get; set; }
        public bool Outsider1 { get; set; }
        public Nullable<DateTime> StartDate { get; set; }
        public string StartDateH { get; set; }
    }
}
