//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Owner
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner()
        {
            this.BirthVacDecs = new HashSet<BirthVacDec>();
            this.DecesionAbsenceNormalDeductions = new HashSet<DecesionAbsenceNormalDeduction>();
            this.DecisionCompanionVacs = new HashSet<DecisionCompanionVac>();
            this.DecisionEndServices = new HashSet<DecisionEndService>();
            this.DecisionNewJobs = new HashSet<DecisionNewJob>();
            this.DecisionNewJobs1 = new HashSet<DecisionNewJob>();
            this.DecisionNormalVacations = new HashSet<DecisionNormalVacation>();
            this.DecisionOutOfDutyGroup2 = new HashSet<DecisionOutOfDutyGroup2>();
            this.DecisionOutOfDutySpends = new HashSet<DecisionOutOfDutySpend>();
            this.DecisionOutOfDutySpend2 = new HashSet<DecisionOutOfDutySpend2>();
            this.DecisionPostmanBonus = new HashSet<DecisionPostmanBonu>();
            this.DecisionReplacementVacations = new HashSet<DecisionReplacementVacation>();
            this.DecisionSingleLegations = new HashSet<DecisionSingleLegation>();
            this.DecisionSingleOutOfDuties = new HashSet<DecisionSingleOutOfDuty>();
            this.DecisionViolations = new HashSet<DecisionViolation>();
            this.DecisionWorkerVacations = new HashSet<DecisionWorkerVacation>();
            this.DialysisVecDecs = new HashSet<DialysisVecDec>();
            this.GivingBirthVacs = new HashSet<GivingBirthVac>();
            this.LegationApplications = new HashSet<LegationApplication>();
            this.Legations = new HashSet<Legation>();
            this.MarriageVacs = new HashSet<MarriageVac>();
            this.MotherHoodVacs = new HashSet<MotherHoodVac>();
            this.TrainingTrxes = new HashSet<TrainingTrx>();
            this.VacationApplications = new HashSet<VacationApplication>();
        }
    
        public int OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPosition { get; set; }
        public byte[] Signature { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BirthVacDec> BirthVacDecs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecesionAbsenceNormalDeduction> DecesionAbsenceNormalDeductions { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionCompanionVac> DecisionCompanionVacs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionEndService> DecisionEndServices { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionNewJob> DecisionNewJobs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionNewJob> DecisionNewJobs1 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionNormalVacation> DecisionNormalVacations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionOutOfDutyGroup2> DecisionOutOfDutyGroup2 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionOutOfDutySpend> DecisionOutOfDutySpends { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionOutOfDutySpend2> DecisionOutOfDutySpend2 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionPostmanBonu> DecisionPostmanBonus { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionReplacementVacation> DecisionReplacementVacations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionSingleLegation> DecisionSingleLegations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionSingleOutOfDuty> DecisionSingleOutOfDuties { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionViolation> DecisionViolations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionWorkerVacation> DecisionWorkerVacations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DialysisVecDec> DialysisVecDecs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GivingBirthVac> GivingBirthVacs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegationApplication> LegationApplications { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Legation> Legations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarriageVac> MarriageVacs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotherHoodVac> MotherHoodVacs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingTrx> TrainingTrxes { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationApplication> VacationApplications { get; set; }
    }
}
