//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PayslipInfo
    {
        public int EmployeeID { get; set; }
        public byte GregorianMonth { get; set; }
        public short GregorianYear { get; set; }
        public string ElementCode { get; set; }
        public string EltezamResponse { get; set; }
    }
}
