//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PaySlip
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaySlip()
        {
            this.ApprovedPayrolls = new HashSet<ApprovedPayroll>();
            this.ApprovedPayrolls1 = new HashSet<ApprovedPayroll>();
            this.BonusEdits = new HashSet<BonusEdit>();
            this.CustomPayrolls = new HashSet<CustomPayroll>();
            this.Employees = new HashSet<Employee>();
            this.SuddenFPs = new HashSet<SuddenFP>();
        }
    
        public byte PaySlipID { get; set; }
        public string PaySlipName { get; set; }
        public byte PaySlipTypeID { get; set; }
        public string ReportName { get; set; }
        public string EmploymentTypeCode { get; set; }
        public Nullable<long> EmpJobClass { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedPayroll> ApprovedPayrolls { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedPayroll> ApprovedPayrolls1 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusEdit> BonusEdits { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomPayroll> CustomPayrolls { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual PaySlipType PaySlipType { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuddenFP> SuddenFPs { get; set; }
    }
}
