//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PermissionsTrxView
    {
        public short Year { get; set; }
        public int PermissionsTrxSerial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public int PermissionTypeId { get; set; }
        public string PermissionTypeName { get; set; }
        public DateTime PermissionDate { get; set; }
        public string PermissionDateH { get; set; }
        public string StartTime { get; set; }
        public decimal StartTimeMod { get; set; }
        public string EndTime { get; set; }
        public decimal EndTimeMod { get; set; }
        public decimal PermissionPeriod { get; set; }
    }
}
