//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PermissionsType
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionsType()
        {
            this.EmpPermissionsDetails = new HashSet<EmpPermissionsDetail>();
            this.EmpPermissionsRs = new HashSet<EmpPermissionsR>();
            this.PermissionsTrxes = new HashSet<PermissionsTrx>();
        }
    
        public int PermissionTypeId { get; set; }
        public string PermissionTypeName { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPermissionsDetail> EmpPermissionsDetails { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPermissionsR> EmpPermissionsRs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionsTrx> PermissionsTrxes { get; set; }
    }
}
