//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PermissionsSettingsD
    {
        public int EmployeeID { get; set; }
        public byte MonthlyCount { get; set; }
        public byte WeeklyCount { get; set; }
        public byte DailyCount { get; set; }
        public short HoursPerMonth { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual AttendTrxEmployee AttendTrxEmployee { get; set; }
        public virtual Department Department { get; set; }
    }
}
