//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PromotionQualified
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromotionQualified()
        {
            this.PromotionQualifiedEmps = new HashSet<PromotionQualifiedEmp>();
        }
    
        public short Serial { get; set; }
        public DateTime TillDate { get; set; }
        public string TillDateH { get; set; }
        public string DocNo { get; set; }
        public string Classes { get; set; }
        public int MemberId1 { get; set; }
        public int MemberId2 { get; set; }
        public Nullable<int> MemberId3 { get; set; }
        public Nullable<int> MemberId4 { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionQualifiedEmp> PromotionQualifiedEmps { get; set; }
    }
}
