//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PromotionQualifiedEmp
    {
        public short Serial { get; set; }
        public int EmpId { get; set; }
        public string ClassificationNo { get; set; }
        public byte ServiceYears { get; set; }
        public byte ServiceMonths { get; set; }
        public byte ServiceDays { get; set; }
        public string DirectTraining { get; set; }
        public string InDirectTraining { get; set; }
        public decimal EducationPoints { get; set; }
        public decimal SeniorityPoints { get; set; }
        public decimal TrainigPoints { get; set; }
        public decimal EvaluationPoints { get; set; }
        public byte CommitteeOpinion { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PromotionQualified PromotionQualified { get; set; }
    }
}
