//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Reminder
    {
        public string UserId { get; set; }
        public short ReminderId { get; set; }
        public string Subject { get; set; }
        public DateTime StartDate { get; set; }
        public string StartDateH { get; set; }
        public DateTime EndDate { get; set; }
        public string EndDateH { get; set; }
        public string Hour { get; set; }
        public byte Priority { get; set; }
        public string Notes { get; set; }
    }
}
