//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class SeniorityTable
    {
        public byte Month { get; set; }
        public decimal Year0 { get; set; }
        public decimal Year1 { get; set; }
        public decimal Year2 { get; set; }
        public decimal Year3 { get; set; }
        public decimal Year4 { get; set; }
        public decimal Year5 { get; set; }
        public decimal Year6 { get; set; }
        public decimal Year7 { get; set; }
        public decimal Year8 { get; set; }
        public decimal Year9 { get; set; }
        public decimal Year10 { get; set; }
        public decimal Year11 { get; set; }
        public decimal Year12 { get; set; }
    }
}
