//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Setting
    {
        public byte BranchId { get; set; }
        public decimal RetirementRatio { get; set; }
        public decimal InsuranceRatio { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public byte WorkDays { get; set; }
        public string CompanyName { get; set; }
        public string SystemDate { get; set; }
        public bool UseAttendance { get; set; }
        public bool SaveBlockedCustomers { get; set; }
        public decimal HighCostAllow { get; set; }
        public byte LegationDays { get; set; }
        public byte MinVacation { get; set; }
        public short MaxVacation { get; set; }
        public byte MinUrgentVacation { get; set; }
        public byte MaxUrgentVacation { get; set; }
        public bool VacationSaving { get; set; }
        public decimal NormalHourRate { get; set; }
        public decimal VacHourRate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> SalaryReviserId { get; set; }
        public Nullable<int> EmpManagerId { get; set; }
        public Nullable<int> DirectorId { get; set; }
        public Nullable<int> FinanceManagerId { get; set; }
        public Nullable<int> AccounttingReviserId { get; set; }
        public string CompanyBankCode { get; set; }
        public string TransFilePath { get; set; }
        public int PaymentNo { get; set; }
        public string AccountNumber { get; set; }
        public string BranchName { get; set; }
        public bool ShowCurrencies { get; set; }
        public bool ShowWeather { get; set; }
        public bool ShowNews { get; set; }
        public byte RefreshInterval { get; set; }
        public bool LinkUsers { get; set; }
        public string ProdK { get; set; }
        public bool RemainderCalc { get; set; }
        public bool AllowOpenTextSalary { get; set; }
        public decimal MaxHours { get; set; }
        public decimal SumHours { get; set; }
        public decimal DayRatio { get; set; }
        public bool MaximizeForms { get; set; }
        public Nullable<int> EmpIDJob { get; set; }
        public Nullable<int> SalaryReviserIdJob { get; set; }
        public Nullable<int> EmpManagerIdJob { get; set; }
        public Nullable<int> DirectorIdJob { get; set; }
        public Nullable<int> FinanceManagerIdJob { get; set; }
        public Nullable<int> AccounttingReviserIdJob { get; set; }
        public string CompanyNameE { get; set; }
        public bool CalcSalaryForForeigns { get; set; }
        public decimal AbsenceHours { get; set; }
        public bool AutoImportAttendData { get; set; }
        public Nullable<int> VacationsDirectorId { get; set; }
        public Nullable<int> BaladiaManager { get; set; }
        public bool CalcServiceDate { get; set; }
        public string sFileName { get; set; }
        public bool EditOutOfDutySalary { get; set; }
        public Nullable<int> PermissionsAdmin { get; set; }
        public bool AllowSavingBankAcc { get; set; }
        public byte WorkersVacations { get; set; }
        public bool PromotionDateUpdated { get; set; }
        public bool ShowEndedVacs { get; set; }
        public bool CalcWorkerOutOfDuty { get; set; }
        public bool CalcRetirementDecimals { get; set; }
        public bool StopTransAll { get; set; }
        public bool AllowEditTransport { get; set; }
        public string BaladiaCode { get; set; }
        public bool CalcNetInsurance { get; set; }
        public bool OutOfDutyNoLimit { get; set; }
        public bool HideVacBalances { get; set; }
        public byte[] Bg { get; set; }
        public Nullable<short> SearchRows { get; set; }
        public bool CalcSaudiOutOfDuty { get; set; }
        public bool ShowAllLegations { get; set; }
        public string AttendMachinePath { get; set; }
        public bool UseNewAttendMachine { get; set; }
        public bool CalcSupportDeduct { get; set; }
        public bool PenaltyOnBasic { get; set; }
        public bool OverrideRaseed { get; set; }
        public bool CalcVacOutOfDuty { get; set; }
        public short EndIdAlertDays { get; set; }
        public bool EditSupportDeduct { get; set; }
        public decimal OutOfDutyRatio { get; set; }
        public decimal SumHoursForeigner { get; set; }
        public decimal OutOfDutyRatioForeigner { get; set; }
        public decimal SupportDeductRatio { get; set; }
        public Nullable<decimal> InTimeDiff { get; set; }
        public Nullable<decimal> OutTimeDiff { get; set; }
        public Nullable<DateTime> UploadFingerPrint { get; set; }
        public bool IgnoreInRec { get; set; }
        public bool IgnoreOutRec { get; set; }
        public Nullable<int> EmpIdVac { get; set; }
        public Nullable<int> EmpIdLeg { get; set; }
        public Nullable<int> EmpIdJobVac { get; set; }
        public Nullable<int> EmpIdJobLeg { get; set; }
        public string HostingServer { get; set; }
        public string HostingDataBase { get; set; }
        public string HostingUserId { get; set; }
        public string HostingPassword { get; set; }
        public bool VacationSms { get; set; }
        public bool ReplacementWorkDays { get; set; }
        public bool ReplacementAccumulate { get; set; }
        public bool TransDedVac { get; set; }
        public string SuddenData { get; set; }
        public bool ExecludeRepVac { get; set; }
        public bool AbsenceDaysCalc { get; set; }
        public bool DaysDeductCalc { get; set; }
        public bool HoursDeductCalc { get; set; }
        public string SectionNo { get; set; }
        public string ChapterNo { get; set; }
        public string BranchNo { get; set; }
        public string DepartmentNo { get; set; }
        public string ManagementNo { get; set; }
        public bool LegationGrg { get; set; }
        public bool DecWorkerVacStopSalary { get; set; }
        public bool GregPayroll { get; set; }
        public bool NewBalanceFirst { get; set; }
        public bool NoWorkerOutOfDuty { get; set; }
        public bool NoWorkerLegations { get; set; }
        public bool MonthDetails { get; set; }
        public Nullable<byte> LastServiceDateAlertM { get; set; }
        public bool VacAppAlerts { get; set; }
        public string AbsenceMsg { get; set; }
        public byte MaxSickVac { get; set; }
        public bool WorkersVacationsNonSaudi { get; set; }
        public byte PermMonthHours { get; set; }
        public decimal MaxPermHours { get; set; }
        public bool LegationOutOfDuty { get; set; }
        public bool AttendanceGrg { get; set; }
        public string SuddenFPSMS { get; set; }
        public bool LinkDecAbsenceDedutWithMonthlySalary { get; set; }
        public bool loansGrg { get; set; }
        public Nullable<short> SubAgencyID { get; set; }
        public string EltezamGuide { get; set; }
        public string PARTY_ID_NUM { get; set; }
        public bool LoansGreg { get; set; }
        public bool PreventNatIdDuplicate { get; set; }
        public decimal InsuRatioForgn { get; set; }
        public bool CompanionVacOutOfDuty { get; set; }
        public byte MaxOutDutyDays { get; set; }
        public string RTMD_HR { get; set; }
        public string SarfFilePath { get; set; }
        public bool StopValidation { get; set; }
        public byte[] Bg2 { get; set; }
    }
}
