//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class TmpAttendTrx2
    {
        public DateTime Date { get; set; }
        public int EmpID { get; set; }
        public string DateH { get; set; }
        public int AttendanceGroupId { get; set; }
        public Nullable<DateTime> InTimeDate { get; set; }
        public string InTime { get; set; }
        public decimal InTimeMod { get; set; }
        public decimal InTimeDiff { get; set; }
        public string strInTimeDiff { get; set; }
        public Nullable<DateTime> OutTimeDate { get; set; }
        public string OutTime { get; set; }
        public decimal OutTimeMod { get; set; }
        public decimal OutTimeDiff { get; set; }
        public string strOutTimeDiff { get; set; }
        public byte AttendTypeID { get; set; }
        public byte LeaveTypeID { get; set; }
        public Nullable<byte> VacationID { get; set; }
        public decimal PermissionInTimeDiff { get; set; }
        public string PermissionInTimeDiffDesc { get; set; }
        public decimal PermissionOutTimeDiff { get; set; }
        public string PermissionOutTimeDiffDesc { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
    
        public virtual AttendanceGroup AttendanceGroup { get; set; }
        public virtual AttendType AttendType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
