//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class TrainingTrxApp
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingTrxApp()
        {
            this.TrainingTrxAppLegationDays = new HashSet<TrainingTrxAppLegationDay>();
        }
    
        public short Year { get; set; }
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public string DecisionNo { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public short Days { get; set; }
        public short TrainingDays { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public bool LegationType { get; set; }
        public Nullable<short> CityId { get; set; }
        public Nullable<byte> OutLegationType { get; set; }
        public string Program { get; set; }
        public string TrainingPlace { get; set; }
        public string Notes { get; set; }
        public bool IncludeSatAndFri { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<short> DecisionsListYear { get; set; }
        public Nullable<short> DecisionsListSerial { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingTrxAppLegationDay> TrainingTrxAppLegationDays { get; set; }
    }
}
