//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class TrainingTrx
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingTrx()
        {
            this.TrainingTrxLegationDays = new HashSet<TrainingTrxLegationDay>();
        }
    
        public short Year { get; set; }
        public byte Month { get; set; }
        public int TrainingSerial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public int EmpID { get; set; }
        public bool LegationType { get; set; }
        public short Days { get; set; }
        public short TrainingDays { get; set; }
        public decimal SumDays { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal Tickets { get; set; }
        public decimal Total { get; set; }
        public decimal Salary { get; set; }
        public Nullable<byte> OutlegationType { get; set; }
        public decimal DaysRatio { get; set; }
        public decimal SumTrainingDays { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public string ReferTo { get; set; }
        public string Program { get; set; }
        public string TrainingTrxId { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<short> CityId { get; set; }
        public byte ExtraTransportAllow { get; set; }
        public bool HasCar { get; set; }
        public string Notes { get; set; }
        public Nullable<short> TrainingTrxAppYear { get; set; }
        public Nullable<int> TrainingTrxAppSerial { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Owner Owner { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingTrxLegationDay> TrainingTrxLegationDays { get; set; }
    }
}
