//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class TrainingTrxAppLegationDay
    {
        public short Year { get; set; }
        public int Serial { get; set; }
        public byte LineNo { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public string DateH { get; set; }
        public string Notes { get; set; }
    
        public virtual TrainingTrxApp TrainingTrxApp { get; set; }
    }
}
