//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class TransToBankLog
    {
        public short Year { get; set; }
        public byte Month { get; set; }
        public short Serial { get; set; }
        public Nullable<DateTime> CreateDate { get; set; }
        public Nullable<byte> BankId { get; set; }
        public Nullable<DateTime> TransDate { get; set; }
        public string TransDateH { get; set; }
        public Nullable<DateTime> DueDate { get; set; }
        public string DueDateH { get; set; }
        public Nullable<int> CountEmployees { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Path { get; set; }
    }
}
