//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class TransToBankLegation
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransToBankLegation()
        {
            this.TransToBankLegationEmps = new HashSet<TransToBankLegationEmp>();
        }
    
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte Bank { get; set; }
        public DateTime TransDate { get; set; }
        public string TransDateH { get; set; }
        public DateTime DueDate { get; set; }
        public string DueDateH { get; set; }
        public Nullable<byte> TransType { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public string TransFilePath { get; set; }
        public Nullable<byte> Cal { get; set; }
        public string Notes { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransToBankLegationEmp> TransToBankLegationEmps { get; set; }
    }
}
