//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class TransToBankEmp
    {
        public int Serial { get; set; }
        public int EmpId { get; set; }
        public decimal Salary { get; set; }
        public decimal OutOfDuty { get; set; }
        public decimal Legation { get; set; }
        public decimal Training { get; set; }
        public decimal Other { get; set; }
        public decimal Total { get; set; }
        public decimal EndOfService { get; set; }
        public decimal Vacations { get; set; }
        public decimal Visa { get; set; }
        public decimal Transport { get; set; }
        public decimal Boarding { get; set; }
        public decimal SalaryInstallment { get; set; }
        public decimal SalaryDifferences { get; set; }
        public decimal Bonus { get; set; }
        public decimal Deductions { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TransToBank TransToBank { get; set; }
    }
}
