//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class User
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool NotActive { get; set; }
        public byte AlertTime { get; set; }
        public bool IgnoreAutoSerial { get; set; }
        public Nullable<short> OnlyMenuId { get; set; }
        public bool LogH { get; set; }
        public byte[] SigImg { get; set; }
        public Nullable<DateTime> PasswordChangeDate { get; set; }
        public bool CanDblQuantity { get; set; }
        public string UserImageURL { get; set; }
        public bool SendLongSMS { get; set; }
        public string PassCode { get; set; }
    }
}
