//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class VacationTrx
    {
        public short Year { get; set; }
        public int Serial { get; set; }
        public int EmpID { get; set; }
        public byte VacationID { get; set; }
        public Nullable<DateTime> FromDate { get; set; }
        public string FromDateH { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public short VacationPeriod { get; set; }
        public Nullable<short> VacationApplicationYear { get; set; }
        public Nullable<int> VacationApplicationSerial { get; set; }
        public Nullable<int> AbsenceNormalDeductionSerial { get; set; }
        public Nullable<int> CompanionVacationSerial { get; set; }
        public Nullable<byte> ReplacementType { get; set; }
        public Nullable<int> DecisionSchoolVacationID { get; set; }
        public Nullable<int> DecisionNormalVacationSerial { get; set; }
        public string EltezamResponse { get; set; }
        public Nullable<short> MrVacSerial { get; set; }
    
        public virtual DecisionNormalVacation DecisionNormalVacation { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual MarriageVac MarriageVac { get; set; }
        public virtual Vacation Vacation { get; set; }
    }
}
