//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class VacationApplicationImage
    {
        public short Year { get; set; }
        public int VacationApplicationSerial { get; set; }
        public int LineNo { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual VacationApplication VacationApplication { get; set; }
    }
}
