//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class VacationBalance
    {
        public int EmpID { get; set; }
        public decimal NormalBalance { get; set; }
        public decimal UrgentBalance { get; set; }
        public decimal ReplacementBalance { get; set; }
        public decimal DeservedNormal { get; set; }
        public decimal TakenNormal { get; set; }
        public decimal DeservedUrgent { get; set; }
        public decimal TakenUrgent { get; set; }
        public decimal DeservedReplacement { get; set; }
        public decimal TakenReplacement { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
