//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class Vacations_38
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> SumDeservedBefore38 { get; set; }
        public Nullable<decimal> TakenBefore38 { get; set; }
        public Nullable<decimal> BalanceBefore38 { get; set; }
        public Nullable<decimal> SumDeservedAfter38 { get; set; }
        public Nullable<decimal> TakenAfter38 { get; set; }
        public Nullable<decimal> BalanceAfter38 { get; set; }
        public Nullable<decimal> ShortVacDeserved { get; set; }
        public Nullable<decimal> ShortVacTaken { get; set; }
        public Nullable<decimal> ShortVacBalance { get; set; }
        public Nullable<decimal> ReplacementVacDeserved { get; set; }
        public Nullable<decimal> ReplacementVacTaken { get; set; }
        public Nullable<decimal> ReplacementVacBalance { get; set; }
    }
}
