//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class VacationTransferD
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VacationTransferD()
        {
            this.VacationTransferDEmps = new HashSet<VacationTransferDEmp>();
        }
    
        public int VTDSerial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public short ToYear { get; set; }
        public string Notes { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationTransferDEmp> VacationTransferDEmps { get; set; }
    }
}
