//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class VacationApplication
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VacationApplication()
        {
            this.DecisionCompanionVacs = new HashSet<DecisionCompanionVac>();
            this.DecisionReplacementVacations = new HashSet<DecisionReplacementVacation>();
            this.DecisionSchoolVacations = new HashSet<DecisionSchoolVacation>();
            this.DecisionSickVacations = new HashSet<DecisionSickVacation>();
            this.VacationApplicationImages = new HashSet<VacationApplicationImage>();
        }
    
        public short Year { get; set; }
        public int VacationApplicationSerial { get; set; }
        public int EmpID { get; set; }
        public byte VacationID { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public short VacationPeriod { get; set; }
        public Nullable<DateTime> ToDate { get; set; }
        public string ToDateH { get; set; }
        public bool CheckApproved { get; set; }
        public Nullable<bool> Deserved { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public string DenyReason { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> SubstituteEmpId { get; set; }
        public bool SubstituteApproval { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string VacSigEmp { get; set; }
        public Nullable<byte> ReplacementType { get; set; }
        public string TargetName { get; set; }
        public Nullable<DateTime> LtrDate { get; set; }
        public string LtrDateH { get; set; }
        public short VacationPeriodNew { get; set; }
        public Nullable<long> ETAVacationID { get; set; }
        public bool HasCar { get; set; }
        public bool CarReceived { get; set; }
        public bool ChiefSignature { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionCompanionVac> DecisionCompanionVacs { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionReplacementVacation> DecisionReplacementVacations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionSchoolVacation> DecisionSchoolVacations { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DecisionSickVacation> DecisionSickVacations { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Owner Owner { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationApplicationImage> VacationApplicationImages { get; set; }
        public virtual Vacation Vacation { get; set; }
    }
}
