//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class VacationSubtraction
    {
        public short Year { get; set; }
        public int Serial { get; set; }
        public int EmpID { get; set; }
        public DateTime FromDate { get; set; }
        public string FromDateH { get; set; }
        public DateTime ToDate { get; set; }
        public string ToDateH { get; set; }
        public decimal SumDeserved { get; set; }
        public Nullable<int> DecisionExceptionVacationID { get; set; }
        public Nullable<int> DecisionSchoolVacationID { get; set; }
        public Nullable<int> DecisionAbsenceDeductionID { get; set; }
        public byte ReplacementType { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
