//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class VacNewBalance
    {
        public int EmpID { get; set; }
        public DateTime ContractDate { get; set; }
        public Nullable<decimal> OldDeserved { get; set; }
        public int OldTaken { get; set; }
        public Nullable<decimal> NewDeserved { get; set; }
        public int NewTaken { get; set; }
        public int Replacement { get; set; }
    }
}
