//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewEmpPromotion
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string ContractDateH { get; set; }
        public string DepartmentName { get; set; }
        public string JobLocationName { get; set; }
        public string JobName { get; set; }
        public Nullable<decimal> StartSalary { get; set; }
        public string ClassName { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPosition { get; set; }
        public int PromotionID { get; set; }
        public byte EnclosureCount { get; set; }
        public string DecisionDateH { get; set; }
        public string CurJobName { get; set; }
        public string CurJobLocationName { get; set; }
        public string CurClassName { get; set; }
        public byte CurDegree { get; set; }
        public string NewJobName { get; set; }
        public string NewJobLocationName { get; set; }
        public string NewClassName { get; set; }
        public byte NewDegree { get; set; }
        public int RecordID { get; set; }
        public string RecordDateH { get; set; }
        public string ApprovedFrom { get; set; }
        public string ApprovedID { get; set; }
        public string ApprovedDateH { get; set; }
        public string CheckRaise { get; set; }
        public string CheckStartWork { get; set; }
        public string StartWorkDateH { get; set; }
        public string StartWorkOwner { get; set; }
    }
}
