//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewEmpDate
    {
        public int EmpID { get; set; }
        public DateTime Date { get; set; }
        public string UmElQuraDate { get; set; }
        public byte MonthUmElQura { get; set; }
        public short YearUmElQura { get; set; }
        public string HijriDate { get; set; }
        public byte MonthHijri { get; set; }
        public short YearHijri { get; set; }
    }
}
