//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewDecisionLegation
    {
        public int DecisionLegationID { get; set; }
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public string PublishedFrom { get; set; }
        public int PublishNumber { get; set; }
        public DateTime PublishDate { get; set; }
        public string PublishDateH { get; set; }
        public string DecesionFrom { get; set; }
        public int DecisionNumber { get; set; }
        public DateTime DecisionDate { get; set; }
        public string DecisionDateH { get; set; }
        public string TransferTo { get; set; }
        public short Period { get; set; }
        public DateTime StartDate { get; set; }
        public string StartDateH { get; set; }
        public string Notes { get; set; }
        public string OwnerName { get; set; }
        public string EmpName { get; set; }
        public string ClassName { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public string JobName { get; set; }
        public string DepartmentName { get; set; }
        public string JobLocationName { get; set; }
    }
}
