//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewVacationList
    {
        public short Year { get; set; }
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public int JobID { get; set; }
        public string JobName { get; set; }
        public string DepartmentName { get; set; }
        public decimal OldNormalVacation { get; set; }
        public decimal NormalVacation { get; set; }
        public decimal TakenNormalVacation { get; set; }
        public decimal NormalBalance { get; set; }
        public decimal OldUrgentVacation { get; set; }
        public decimal UrgentVacation { get; set; }
        public decimal TakenUrgentVacation { get; set; }
        public decimal UrgentBalance { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<short> VacationPeriod { get; set; }
        public string FromDateH { get; set; }
    }
}
