//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewDecisionBonu
    {
        public int DecisionBonusID { get; set; }
        public int Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public string DependOn { get; set; }
        public int ApprovalNo { get; set; }
        public DateTime ApprovalDate { get; set; }
        public string ApprovalDateH { get; set; }
        public int TurnNo { get; set; }
        public DateTime TurnStart { get; set; }
        public string TurnStartH { get; set; }
        public DateTime TurnEnd { get; set; }
        public string TurnEndH { get; set; }
        public string Notes { get; set; }
        public string OwnerName { get; set; }
        public string EmpName { get; set; }
        public string JobName { get; set; }
        public string JobLocationName { get; set; }
        public string DepartmentName { get; set; }
        public string ClassName { get; set; }
        public string ContractDateH { get; set; }
    }
}
