//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewDecisionAllowance
    {
        public int DecisionAllowanceID { get; set; }
        public int Serial { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public string OwnerName { get; set; }
        public string EmpName { get; set; }
        public string JobName { get; set; }
        public string ClassName { get; set; }
        public Nullable<byte> DegreeID { get; set; }
        public string DepartmentName { get; set; }
        public string JobLocationName { get; set; }
        public string PlaceName { get; set; }
        public int LetterId { get; set; }
        public decimal Ratio { get; set; }
        public decimal Allowance { get; set; }
        public string StartDateH { get; set; }
    }
}
