//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewEmp
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public int JobID { get; set; }
        public string JobName { get; set; }
        public byte ClassID { get; set; }
        public byte DegreeID { get; set; }
        public decimal StartSalary { get; set; }
        public decimal YearlyIncrease { get; set; }
        public decimal TransportAllow { get; set; }
        public decimal InsideLegationAllow { get; set; }
        public decimal OutsideLegationAllow { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public byte JobLocationID { get; set; }
        public string JobLocationName { get; set; }
        public Nullable<byte> FormingNumer { get; set; }
        public decimal FirstSalary { get; set; }
        public decimal NatureAllow { get; set; }
        public Nullable<decimal> NatureAllowVal { get; set; }
        public byte PaySlipTypeID { get; set; }
    }
}
