//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewSalaryListSummary
    {
        public short السنة { get; set; }
        public byte الشهر { get; set; }
        public string البيان { get; set; }
        public Nullable<decimal> موظفين { get; set; }
        public Nullable<decimal> مستخدمين { get; set; }
        public Nullable<decimal> متعاقدين { get; set; }
        public Nullable<decimal> العمال_السعوديين { get; set; }
        public Nullable<decimal> العمال_الأجانب { get; set; }
        public Nullable<decimal> نقل { get; set; }
        public Nullable<decimal> ضرر { get; set; }
        public Nullable<decimal> طبيعة_عمل { get; set; }
        public Nullable<decimal> الإجمالى { get; set; }
        public Nullable<decimal> تقاعد { get; set; }
        public Nullable<decimal> تأمينات { get; set; }
        public Nullable<decimal> جزاءات { get; set; }
        public Nullable<decimal> بنك { get; set; }
        public Nullable<decimal> أخرى { get; set; }
        public Nullable<decimal> إجمالى_حسميات { get; set; }
        public Nullable<decimal> الصافى { get; set; }
    }
}
