//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewAllEmpData
    {
        public int كود_الموظف { get; set; }
        public string إسم_الموظف { get; set; }
        public short كود_الجنسية { get; set; }
        public string الجنسية { get; set; }
        public Nullable<DateTime> BirthDate { get; set; }
        public string تاريخ_الميلاد { get; set; }
        public string مكان_الميلاد { get; set; }
        public byte كود_الديانة { get; set; }
        public string الديانة { get; set; }
        public byte كود_الحالة_الاجتماعية { get; set; }
        public string الحالة_الاجتماعية { get; set; }
        public string رقم_السجل_المدنى { get; set; }
        public string جهة_الاصدار { get; set; }
        public Nullable<DateTime> IDDate { get; set; }
        public string تاريخ_الاصدار { get; set; }
        public Nullable<DateTime> IDEndDate { get; set; }
        public string تاريخ_الانتهاء { get; set; }
        public Nullable<byte> رمز_الكادر { get; set; }
        public string الكادر { get; set; }
        public string رقم_قرار_التعيين { get; set; }
        public Nullable<DateTime> ContractDate { get; set; }
        public string تاريخ_المباشرة { get; set; }
        public int رمز_الوظيفة { get; set; }
        public string الوظيفة { get; set; }
        public string الرقم_التأمينى { get; set; }
        public byte المرتبة { get; set; }
        public byte الدرجة { get; set; }
        public decimal الراتب { get; set; }
        public decimal بدل_الإنتقال { get; set; }
        public decimal بدل_انتداب_داخلى { get; set; }
        public decimal بدل_انتداب_خارجى { get; set; }
        public decimal بدل_طبيعة_عمل { get; set; }
        public decimal بدل_ضرر { get; set; }
        public decimal بدلات_أخرى { get; set; }
        public Nullable<byte> رقم_التشكيل { get; set; }
        public Nullable<DateTime> ClassDate { get; set; }
        public string تاريخ_حصول_المرتبة { get; set; }
        public Nullable<byte> رمز_جهة_الوظيفة { get; set; }
        public string جهة_الوظيفة { get; set; }
        public int رمز_الادارة { get; set; }
        public string الادارة { get; set; }
        public Nullable<byte> رمز_المسير { get; set; }
        public string المسير { get; set; }
        public bool تحويل_للبنك { get; set; }
        public byte رمز_البنك { get; set; }
        public string البنك { get; set; }
        public string رقم_الحساب { get; set; }
        public Nullable<DateTime> RetirementDate { get; set; }
        public string تاريخ_التقاعد { get; set; }
        public Nullable<DateTime> PromotionDate { get; set; }
        public string تاريخ_اخر_ترقية { get; set; }
        public Nullable<byte> رمز_المؤهل_الدراسى { get; set; }
        public string المؤهل_الدراسى { get; set; }
        public Nullable<DateTime> CertificateDate { get; set; }
        public string تاريخ_المؤهل_الدراسى { get; set; }
        public string التخصص { get; set; }
        public string المدرسة___الجامعة { get; set; }
    }
}
