//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewDecisionStopHand
    {
        public int DecisionStopHandID { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public byte EnclosureCount { get; set; }
        public int Owner { get; set; }
        public int EmpId { get; set; }
        public string Subject { get; set; }
        public int SubjectNumber { get; set; }
        public DateTime SubjectDate { get; set; }
        public string SubjectDateH { get; set; }
        public string SubjectReason { get; set; }
        public DateTime StartDate { get; set; }
        public string StartDateH { get; set; }
        public string Notes { get; set; }
        public string DecisionNo { get; set; }
        public string OwnerName { get; set; }
        public string EmpName { get; set; }
        public string ClassName { get; set; }
        public string JobName { get; set; }
        public string JobLocationName { get; set; }
        public string DepartmentName { get; set; }
    }
}
