//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class ViewSalaryList
    {
        public int رقم_الموظف { get; set; }
        public string إسم_الموظف { get; set; }
        public string الوظيفة { get; set; }
        public byte المرتبة { get; set; }
        public byte الدرجة { get; set; }
        public decimal الراتب_الأساسى { get; set; }
        public decimal بدل_انتقال { get; set; }
        public decimal طبيعة_عمل { get; set; }
        public Nullable<decimal> C10___بدل { get; set; }
        public decimal الإجمالى { get; set; }
        public decimal تقاعد { get; set; }
        public decimal البنك { get; set; }
        public Nullable<decimal> حسميات_أخرى { get; set; }
        public decimal إجمالى_الحسميات { get; set; }
        public decimal صافى_الراتب { get; set; }
        public string ملاحظات { get; set; }
    }
}
