//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class WorkersDecision
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkersDecision()
        {
            this.WorkersDecisionsEmps = new HashSet<WorkersDecisionsEmp>();
        }
    
        public short Serial { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public string Notes { get; set; }
        public string DecisionNo { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkersDecisionsEmp> WorkersDecisionsEmps { get; set; }
    }
}
