//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.Data.Entites.Payroll
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class YearlyIncreaseD
    {
        public short Year { get; set; }
        public int EmpId { get; set; }
        public byte ClassID { get; set; }
        public byte DegreeID { get; set; }
        public decimal StartSalary { get; set; }
        public byte NewClassID { get; set; }
        public byte NewDegreeID { get; set; }
        public decimal NewStartSalary { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual YearlyIncrease YearlyIncrease { get; set; }
    }
}
