// <auto-generated />
namespace MaintenanceSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addrelationInCarEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrelationInCarEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202306201557131_addrelationInCarEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
