//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.DataTajDB.Entites.TajDB
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class BlackListOld
    {
        public byte SystemId { get; set; }
        public int BlackListSerial { get; set; }
        public string CustomerId { get; set; }
        public DateTime Date { get; set; }
        public string DateH { get; set; }
        public Nullable<byte> ReasonId { get; set; }
        public string UserId { get; set; }
        public string Notes { get; set; }
        public string CancelUserId { get; set; }
        public Nullable<DateTime> CancelDate { get; set; }
        public string CancelDateH { get; set; }
        public Nullable<short> VlnYear { get; set; }
        public Nullable<int> VlnSerial { get; set; }
        public string PauseUserId { get; set; }
        public Nullable<DateTime> PauseDate { get; set; }
        public string PauseDateH { get; set; }
        public Nullable<byte> ReasonTypeId { get; set; }
        public Nullable<short> ClctYear { get; set; }
        public Nullable<int> ClctSerial { get; set; }
    }
}
