//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.DataTajDB.Entites.TajDB
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class BranchesPerm
    {
        public string UserId { get; set; }
        public short BranchId { get; set; }
        public bool DefaultBranch { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
    }
}
