//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.DataTajDB.Entites.TajDB
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class MyDate
    {
        public DateTime Date { get; set; }
        public Nullable<long> BioStarDate { get; set; }
        public string UmElQuraDate { get; set; }
        public Nullable<byte> MonthUmElQura { get; set; }
        public Nullable<short> YearUmElQura { get; set; }
        public string HijriDate { get; set; }
        public Nullable<byte> MonthHijri { get; set; }
        public Nullable<short> YearHijri { get; set; }
        public Nullable<byte> WeekDay { get; set; }
        public Nullable<short> YearUm2 { get; set; }
        public string UmElQuraDate2 { get; set; }
        public string HijriDate2 { get; set; }
        public Nullable<short> YearUm4 { get; set; }
        public string UmElQuraDate4 { get; set; }
        public string HijriDate4 { get; set; }
    }
}
