//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.DataTajDB.Entites.TajDB
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class PhoneIndex
    {
        public string UserId { get; set; }
        public short PhoneIndexId { get; set; }
        public string PhoneIndexName { get; set; }
        public byte PhoneGroupId { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string WebSite { get; set; }
        public string Notes { get; set; }
        public byte[] Image { get; set; }
    
        public virtual PhoneGroup PhoneGroup { get; set; }
    }
}
