//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.DataTajDB.Entites.TajDB
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class SearchField
    {
        public string Field { get; set; }
        public string SearchField1 { get; set; }
        public string Caption { get; set; }
        public string Table { get; set; }
        public Nullable<byte> Order { get; set; }
        public bool Selected { get; set; }
    }
}
