//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSystem.DataTajDB.Entites.TajDB
{
    using global::System;  using global::System.Diagnostics.CodeAnalysis;
    using global::System.Collections.Generic;
    
    public partial class SmsMessage
    {
        public long SmsId { get; set; }
        public byte SystemId { get; set; }
        public string UserId { get; set; }
        public DateTime Date { get; set; }
        public string MobileNo { get; set; }
        public string Text { get; set; }
        public byte Sent { get; set; }
        public string ETAUserName { get; set; }
        public byte Result { get; set; }
        public Nullable<DateTime> SentTime { get; set; }
        public Nullable<int> SuddenFPSerial { get; set; }
        public string ResultMsg { get; set; }
    
        public virtual System System { get; set; }
        public virtual User User { get; set; }
    }
}
